# Generated by Django 3.1.4 on 2020-12-24 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook', to=settings.AUTH_USER_MODEL)),
                ('linkedin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin', to=settings.AUTH_USER_MODEL)),
                ('twitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
