# Generated by Django 3.1.4 on 2020-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201227_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(),
        ),
    ]
