# Generated by Django 3.1.4 on 2021-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201227_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='users_photos/%Y/%m/%d/'),
        ),
    ]
